### ISSUE TITLE
Dosya ismi içeri aktarılan modülle aynı isimde olmamalı

### ISSUE THREAD

**Issue by maidis** [melike35/holidays-between-2-days#1]
```bash
Traceback (most recent call last):
  File "holidays.py", line 2, in <module>
    import holidays
  File "/home/maidis/Downloads/holidays-between-2-days-main/holidays.py", line 6, in <module>
    tr_holidays = holidays.Turkey()
AttributeError: partially initialized module 'holidays' has no attribute 'Turkey' (most likely due to a circular import)
```
https://stackoverflow.com/questions/59762996/how-to-fix-attributeerror-partially-initialized-module

**Comment by melike35** [comment]
ilk defa karsılastım, dikkatin icin tesekkurler duzeltiyorum  @maidis
